releases/20180603151338/config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root "articles#index"
  resources :articles, path: :post
end

releases/20180603151338/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

releases/20180603151338/app/models/article.rb
class Article < ApplicationRecord
  belongs_to :series
end

releases/20180603151338/app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase

  delegate :url, :current_path, :content_type, to: :data

  validates :data, presence: true
end

releases/20180603151338/app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  mount_uploader :data, CkeditorAttachmentFileUploader, mount_on: :data_file_name

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

releases/20180603151338/app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  mount_uploader :data, CkeditorPictureUploader, mount_on: :data_file_name

  def url_content
    url(:content)
  end
end

releases/20180603151338/app/models/series.rb
class Series < ApplicationRecord

  has_many :articles

end

releases/20180603151338/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

releases/20180603151338/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  def index
    @articles = Article.order(created_at: :desc)
    response.headers["Expires"] = 1.year.from_now.httpdate
  end

  def show
    @articles = Article.find(params[:id])
    @articleslast = Article.order(created_at: :desc).limit(4)
    response.headers["Expires"] = 1.year.from_now.httpdate
  end

  def new
    @articles = Article.new
    @series = Series.all
  end

  def create
    @articles = Article.new(resource_params)
    @articles.save
    redirect_to root_path
  end

  def edit
    @articles = Article.find(params[:id])
    @series = Series.all
  end

  def update
    @articles = Article.find(params[:id])
    @articles.update(resource_params)
    redirect_to root_path
  end



  def resource_params
    params.require(:article).permit(:title, :content, :description, :keywords, :tags, :image, :series_id)
  end

end

releases/20180603151338/app/helpers/application_helper.rb
module ApplicationHelper
end

releases/20180603151338/app/views/articles/edit.html.erb
<section class="section-padding-70">
            <div class="container">

              <%= form_for @articles do |f| %>
              <form>

                <div class="row">
                  <div class="col-md-4">
                    <div class="form-group">
                      <%= f.label :title %>
                      <%= f.text_field :title, class: "form-control"  %>
                    </div>

                  </div><!-- /.col-md-4 -->

                  <div class="col-md-4">
                    <div class="form-group">
                      <%= f.label :keywords %>
                      <%= f.text_field :keywords, class: "form-control" %>
                    </div>
                  </div><!-- /.col-md-4 -->

                  <div class="col-md-4">
                    <div class="form-group">
                      <%= f.label :tags %>
                      <%= f.text_field :tags, class: "form-control" %>
                    </div>
                  </div><!-- /.col-md-4 -->

                </div><!-- /.row -->
                <div class="row">
                  <div class="col-md-6">
                    <div class="form-group">
                      <%= f.label :image %>
                      <%= f.text_field :image, class: "form-control" %>
                    </div>
                  </div><!-- /.col-md-4 -->

                  <div class="col-md-6">
                    <div class="form-group ">
                      <%= f.label :series %>
                      <%= f.collection_select(:series_id, @series, :id, :title, {:prompt=>true}, {:class=>'form-control'}) %>
                    </div>
                  </div><!-- /.col-md-4 -->
                </div>

                <div class="form-group">
                  <%= f.label :content %>
                  <%= f.text_area :content, placeholder: "Your Content", class: "form-control" %>
                </div>

                <div class="form-group">
                  <%= f.label :description %>
                  <%= f.text_area :description, class: "form-control" %>
                </div>

                  <div class="text-right">
                      <%= f.submit 'save', class: "btn btn-primary" %>
                  </div>
              </form>
              <% end %>



            </div>
        </section>

releases/20180603151338/app/views/articles/index.html.erb
        <section class="section-padding-70">
            <div class="container">
                <div class="row">
                    <div class="col-md-8">
                        <div class="post-content">



                            <article class="post-wrapper transition mb-20">
                              <div class="transition">
                                <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
                                <!-- honeyfact -->
                                <ins class="adsbygoogle"
                                   style="display:block"
                                   data-ad-client="ca-pub-4268093070731551"
                                   data-ad-slot="5117010229"
                                   data-ad-format="auto"></ins>
                                <script>
                                (adsbygoogle = window.adsbygoogle || []).push({});
                                </script>
                              </div>
                          </article>



                            <% @articles.each do |b| %>
                            <div class="col-md-6 mb-30">
                                <article class="post-wrapper transition mb-20">
                                    <header class="post-header">
                                        <div class="post-thumbnail">
                                            <%= link_to article_path(b) do %>
                                                <%= image_tag "blog-img-4.jpg" %>
                                            <% end %>
                                        </div>
                                    </header>
                                    <div class="blog-content transition">
                                        <div class="blog-date">
                                            <span><%= b.created_at.strftime("%d %b %Y") %></span>
                                        </div>

                                        <div class="entry-header mb-20">
                                          <%= link_to article_path(b) do %>
                                            <h2 style="font-size: 120%; line-height: 35px;">
                                                <%= b.title  %>
                                            </h2>
                                          <% end %>
                                        </div>
                                        <div class="blog-autthor">
                                            <a href="#"><span>BY</span> SATRIYO UNGGUL</a>
                                        </div>
                                    </div>
                                </article>
                            </div>
                            <% end %>

                        </div> <!-- /.post-content -->

                        <!-- pagination -->
                        <div class="page-pagination">
                            <nav aria-label="Page navigation">

                            </nav>
                        </div>
                        <!-- pagination -->


                    </div> <!-- /.col-md-8 -->

                    <div class="col-md-4">
                      <div class="tt-sidebar-wrapper">
                      <%= render 'layouts/widget' %>
                      <%= render 'layouts/widgetiklan' %>


                      </div> <!-- /.tt-sidebar-wrapper -->
                    </div> <!-- /.col-md-4 -->
                </div> <!-- /.row -->
            </div>
        </section>

releases/20180603151338/app/views/articles/new.html.erb
<section class="section-padding-70">
            <div class="container">

              <%= form_for @articles do |f| %>
              <form>

                <div class="row">
                  <div class="col-md-4">
                    <div class="form-group">
                      <%= f.label :title %>
                      <%= f.text_field :title, class: "form-control"  %>
                    </div>

                  </div><!-- /.col-md-4 -->

                  <div class="col-md-4">
                    <div class="form-group">
                      <%= f.label :keywords %>
                      <%= f.text_field :keywords, class: "form-control" %>
                    </div>
                  </div><!-- /.col-md-4 -->

                  <div class="col-md-4">
                    <div class="form-group">
                      <%= f.label :tags %>
                      <%= f.text_field :tags, class: "form-control" %>
                    </div>
                  </div><!-- /.col-md-4 -->

                </div><!-- /.row -->
                <div class="row">
                  <div class="col-md-6">
                    <div class="form-group">
                      <%= f.label :image %>
                      <%= f.text_field :image, class: "form-control" %>
                    </div>
                  </div><!-- /.col-md-4 -->

                  <div class="col-md-6">
                    <div class="form-group ">
                      <%= f.label :series %>
                      <%= f.collection_select(:series_id, @series, :id, :title, {:prompt=>true}, {:class=>'form-control'}) %>
                    </div>
                  </div><!-- /.col-md-4 -->
                </div>

                <div class="form-group">
                  <%= f.label :content %>
                  <%= f.cktext_area :content, placeholder: "Your Content", class: "form-control" %>
                </div>

                <div class="form-group">
                  <%= f.label :description %>
                  <%= f.text_area :description, class: "form-control" %>
                </div>

                  <div class="text-right">
                      <%= f.submit 'save', class: "btn btn-primary" %>
                  </div>
              </form>
              <% end %>



            </div>
        </section>

releases/20180603151338/app/views/articles/show.html.erb
<section class="section-padding-70">
    <div class="container">
        <div class="row">
            <div class="col-md-8">
                <div class="single-post post-content">

                    <article class="post-wrapper single-post-wrapper transition mb-50">
                        <header class="post-header">
                            <div class="post-thumbnail">
                                <a href="#">
                                    <%= image_tag "blog-img-4.jpg" %>
                                </a>
                            </div>
                        </header>
                        <div class="blog-content transition">
                            <div class="entry-header mb-20">
                                <h1>
                                    <%= @articles.title %>
                                </h1>
                                <em><%= @articles.created_at.strftime("%d %B %Y, Pukul %H:%M") %>, Series: <%= @articles.series.title %></em>

                                <div class="mt-20">
                                <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
                                <!-- honeyfact -->
                                <ins class="adsbygoogle"
                                   style="display:block"
                                   data-ad-client="ca-pub-4268093070731551"
                                   data-ad-slot="5117010229"
                                   data-ad-format="auto"></ins>
                                <script>
                                (adsbygoogle = window.adsbygoogle || []).push({});
                                </script>
                                </div>
                            </div>
                            <div class="entry-content link-arrow-ltr">

                                <p><%= @articles.content %></p>

                                <em>Tags: <%= @articles.tags %></em>
                            </div>
                        </div>
                    </article>

                </div> <!-- /.post-content -->

                <div class="mb-50" %>
                  <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
                  <!-- honeyfact -->
                  <ins class="adsbygoogle"
                     style="display:block"
                     data-ad-client="ca-pub-4268093070731551"
                     data-ad-slot="5117010229"
                     data-ad-format="auto"></ins>
                  <script>
                  (adsbygoogle = window.adsbygoogle || []).push({});
                  </script>
                </div>

                <!-- post author wrapper -->
                <div class="post-author-wrapper mb-50">
                    <div class="post-author-img">
                        <img src="http://zynau.com/uploads/ckeditor/pictures/2/content_rio.jpg" alt="Satriyo Unggul Wicaksono" width="40%">
                    </div>
                    <div class="post-author-intro">
                        <div class="post-author-content">
                            <h3><a href="#">Satriyo Unggul Wicaksono</a></h3>
                            <p>Hai, Saya menekuni bidang teknologi. Ikuti terus tulisan saya di <b>Purwa.id</b> !</p>
                        </div>
                        <ul class="post-author-social-link tt-animate ltr list-inline">
                            <li>
                                <a href="https://www.facebook.com/satriyo.u.wicaksono" class=""><i class="fa fa-facebook facebook"></i></a>
                            </li>

                            <li>
                                <a href="https://www.facebook.com/satriyo.u.wicaksono" class=""><i class="fa fa-twitter twitter"></i></a>
                            </li>

                            <li>
                                <a href="https://www.linkedin.com/in/satriyounggulwicaksono/" class=""><i class="fa fa-linkedin linkedin"></i></a>
                            </li>
                        </ul>
                    </div>
                </div>
                <!-- post author wrapper -->


                <!-- comment and reaply -->
                <div class="comment-wrapper">
                    <div class="comment-tab">

                        <!-- Nav tabs -->

                        <!-- tab panels -->
                        <div class="panel-body">
                            <div class="tab-content">

                                <div role="tabpanel" class="tab-pane fade active in" id="default-comment">
                                    <div class="comment-respond mt-30">

                                      <div id="disqus_thread"></div>
                                        <script>

                                        /**
                                        *  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
                                        *  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables*/
                                        /*
                                        var disqus_config = function () {
                                        this.page.url = PAGE_URL;  // Replace PAGE_URL with your page's canonical URL variable
                                        this.page.identifier = PAGE_IDENTIFIER; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
                                        };
                                        */
                                        (function() { // DON'T EDIT BELOW THIS LINE
                                        var d = document, s = d.createElement('script');
                                        s.src = 'https://purwaid.disqus.com/embed.js';
                                        s.setAttribute('data-timestamp', +new Date());
                                        (d.head || d.body).appendChild(s);
                                        })();
                                        </script>
                                        <noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
                                    </div> <!-- /.comment-resond -->

                                </div>


                            </div> <!-- /.tab-content -->


                        </div> <!-- /.panel-body -->

                    </div> <!-- /.comment-tab -->

                </div>
                <!-- comment and reaply -->


            </div> <!-- /.col-md-8 -->

            <div class="col-md-4">
                <div class="tt-sidebar-wrapper">
                  <%= render 'layouts/widget' %>
                  <%= render 'layouts/widgetlastpost' %>
                  <%= render 'layouts/widgetiklan' %>
                </div> <!-- /.tt-sidebar-wrapper -->
            </div> <!-- /.col-md-4 -->
        </div> <!-- /.row -->
    </div>
</section>